name: Publish

on:
  release:
    types: 
      - created

jobs:
  tornado-securecookie-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [11, 12, 13, 14]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: install dependencies
      run: yarn install
    - name: run tests
      run: yarn test

  publish:
    needs: 
      - tornado-securecookie-test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: set version envvar
          run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
        - name: set release version on package.json
          run: sed -i.bak 's/0\.0\.0/'$RELEASE_VERSION'/g' package.json
        - name: check package
          run: cat package.json
        - uses: actions/setup-node@v1
          with:
            node-version: 13
        - name: install dependencies
          run: yarn install
        - name: run tests one more time
          run: yarn test
        - uses: JS-DevTools/npm-publish@v1
          with:
            token: ${{ secrets.NPM_TOKEN }}
